sudo: false
dist: trusty
language: node_js
jobs:
  fast_finish: true
  allow_failures:
    - env: WEBPACK_VERSION=canary
  include:
    - &current
      stage: Webpack tests (current node)
      node_js: 11
      env: WEBPACK_VERSION=latest JOB_PART=test
      script: npm run travis:$JOB_PART

    - <<: *current
      node_js: 11
      env: WEBPACK_VERSION=3 JOB_PART=test
      script: npm run travis:$JOB_PART

    - &old
      stage: Webpack tests (old node)
      node_js: 6
      env: WEBPACK_VERSION=latest JOB_PART=test
      script: npm run travis:$JOB_PART

    - <<: *old
      node_js: 10
      env: WEBPACK_VERSION=3 JOB_PART=test
      script: npm run travis:$JOB_PART

    - <<: *old
      node_js: 8
      env: WEBPACK_VERSION=latest JOB_PART=test
      script: npm run travis:$JOB_PART

    - stage: Webpack tests (canary, current node)
      before_script: npm i --no-save git://github.com/webpack/webpack.git#master
      script: npm run travis:$JOB_PART
      node_js: 11
      env: WEBPACK_VERSION=canary JOB_PART=test
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
  - 'if [[ `npm -v` != 5* ]]; then npm i -g npm@^5.0.0; fi'
  - npm install -g greenkeeper-lockfile@1
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX=g++-4.8; fi
  - export CXX=g++
  - export CC=gcc
  - nvm --version
  - node --version
  - npm --version
before_script:
  - |-
    if [ "$WEBPACK_VERSION" ]; then
      npm i --no-save webpack@$WEBPACK_VERSION
    fi
  - greenkeeper-lockfile-update
after_script:
  - greenkeeper-lockfile-upload
script:
  - 'npm run travis:$JOB_PART'
